FROM python:3.12-slim as build

WORKDIR /app

COPY . /app

RUN pip install --prefix=/install Flask 

FROM gcr.io/distroless/python3

COPY --from=build /install /usr/local

COPY . .

EXPOSE 5000

CMD ["python3", "app.py"]



