FROM ubuntu:latest

WORKDIR /app

COPY . /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv 


RUN python3 -m venv venv && \
    . venv/bin/activate 

RUN pip install Flask --break-system-packages

CMD ["python3", "app.py"]



